# Generated by Django 3.0.8 on 2021-03-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=4, null=True)),
                ('employeetype', models.CharField(blank=True, max_length=2, null=True)),
                ('timesheetdate', models.DateField(blank=True, null=True)),
                ('inout', models.IntegerField(blank=True, null=True)),
                ('timepunch', models.TimeField(blank=True, null=True)),
                ('createdby', models.CharField(blank=True, max_length=50, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('machinename', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transaction_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(blank=True, max_length=4, null=True)),
                ('timesheetdate', models.DateField(blank=True, null=True)),
                ('halfday', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
