# Generated by Django 3.0.8 on 2021-03-25 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhi_id', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('employee_id', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.CharField(blank=True, max_length=20, null=True)),
                ('pic', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('access', models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amonitoring_accounts.UserAccess')),
            ],
        ),
    ]
