# Generated by Django 3.0.8 on 2021-01-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_accounts', '0002_auto_20210118_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
