# Generated by Django 3.0.8 on 2021-01-19 05:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_accounts', '0003_auto_20210118_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='color',
            field=colorfield.fields.ColorField(default=' #4db29e ', max_length=18),
        ),
    ]
