# Generated by Django 3.0.8 on 2021-01-20 00:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_accounts', '0004_auto_20210119_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
