# Generated by Django 3.0.8 on 2021-02-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_status_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_status_description', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Employee Status Code',
            },
        ),
        migrations.CreateModel(
            name='project_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code_description', models.CharField(max_length=25, unique=True)),
                ('project_code_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Project Code',
            },
        ),
    ]
