# Generated by Django 2.2.5 on 2020-06-26 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrg_tm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transacations',
        ),
    ]
