# Generated by Django 2.2.5 on 2020-06-30 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrg_tm', '0003_transacations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transacations',
        ),
    ]
