# Generated by Django 2.2.5 on 2020-07-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrg_tm', '0007_transaction_info_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transaction_info_new',
        ),
    ]
