# Generated by Django 3.0.8 on 2020-11-17 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims_main', '0003_user_detail_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ref_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_description', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Reference Unit',
                'verbose_name_plural': 'Reference Unit',
            },
        ),
        migrations.CreateModel(
            name='ref_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=15, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.ref_unit')),
            ],
            options={
                'verbose_name': 'Reference Area',
            },
        ),
    ]
