# Generated by Django 3.0.8 on 2020-11-18 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims_main', '0007_auto_20201117_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_icn',
            name='area_lead',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 6}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_lead', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='iso_controller',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iso_controller', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='mhi_sv',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mhi_sv', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='pfa_checker',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 10}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfa_checker', to='ims_main.user_detail'),
        ),
    ]
