# Generated by Django 3.0.8 on 2020-11-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_main', '0008_auto_20201118_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ref_mhi_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhi_approve_status_short', models.CharField(max_length=50)),
                ('mhi_approve_status_long', models.CharField(max_length=100)),
                ('model_status', models.CharField(max_length=20)),
                ('mhi_code', models.CharField(max_length=5)),
                ('sort_order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Reference MHI Status',
                'verbose_name_plural': 'Reference MHI Status',
            },
        ),
    ]
