# Generated by Django 3.0.8 on 2020-11-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_main', '0012_tbl_note1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_icn',
            options={'verbose_name': 'ICN Table', 'verbose_name_plural': 'ICN Table'},
        ),
        migrations.AlterModelOptions(
            name='tbl_note1',
            options={'verbose_name': 'Issue Date', 'verbose_name_plural': 'Issue Date'},
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='npd',
            field=models.FloatField(default=0),
        ),
    ]
