# Generated by Django 3.0.8 on 2020-11-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_main', '0013_auto_20201122_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ref_hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_code', models.CharField(blank=True, max_length=10, null=True)),
                ('hold_description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Reference Hold',
                'verbose_name_plural': 'Reference Hold',
            },
        ),
    ]
