# Generated by Django 3.0.8 on 2020-11-23 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims_main', '0014_ref_hold'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_note2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=250, null=True)),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.ref_hold')),
                ('icn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.tbl_icn')),
            ],
            options={
                'verbose_name': 'Hold List',
                'verbose_name_plural': 'Hold List',
            },
        ),
    ]
