# Generated by Django 3.0.8 on 2020-11-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_main', '0015_tbl_note2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_icn',
            name='icn_status',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('REV', 'REV'), ('VOID', 'VOID')], default='NEW', max_length=6, null=True),
        ),
    ]
