# Generated by Django 3.0.8 on 2021-02-16 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_ref', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.CharField(max_length=4, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mhi_id', models.CharField(blank=True, max_length=12, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=6, null=True)),
                ('picture', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('employee_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_ref.employee_status_code', to_field='employee_status_description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_ref.project_code', to_field='project_code_description')),
            ],
        ),
    ]
