# Generated by Django 3.0.8 on 2021-02-03 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ims_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_extract_folder', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'IMS Setting',
            },
        ),
        migrations.CreateModel(
            name='ref_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Reference Area',
            },
        ),
        migrations.CreateModel(
            name='ref_hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_code', models.CharField(blank=True, max_length=10, null=True)),
                ('hold_description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Reference Hold',
                'verbose_name_plural': 'Reference Hold',
            },
        ),
        migrations.CreateModel(
            name='ref_mhi_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhi_approve_status_short', models.CharField(max_length=50)),
                ('mhi_approve_status_long', models.CharField(max_length=100)),
                ('model_status', models.CharField(max_length=20)),
                ('mhi_code', models.CharField(max_length=5)),
                ('sort_order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Reference MHI Status',
                'verbose_name_plural': 'Reference MHI Status',
            },
        ),
        migrations.CreateModel(
            name='ref_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_description', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Reference Unit',
                'verbose_name_plural': 'Reference Unit',
            },
        ),
        migrations.CreateModel(
            name='ref_user_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_access_description', models.CharField(blank=True, max_length=20, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reference User Access',
                'verbose_name_plural': 'Reference User Access',
            },
        ),
        migrations.CreateModel(
            name='tbl_icn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icn', models.CharField(max_length=5, unique=True)),
                ('line_id', models.CharField(max_length=20)),
                ('latest_issue_date', models.DateField(blank=True, null=True)),
                ('npd', models.FloatField(default=0)),
                ('icn_status', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('REV', 'REV'), ('VOID', 'VOID')], default='NEW', max_length=6, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.ref_area')),
            ],
            options={
                'verbose_name': 'ICN Table',
                'verbose_name_plural': 'ICN Table',
            },
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(blank=True, max_length=20, null=True)),
                ('user_access', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ims_main.ref_user_access')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Detail',
            },
        ),
        migrations.CreateModel(
            name='tbl_note2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=250, null=True)),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.ref_hold')),
                ('icn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.tbl_icn')),
            ],
            options={
                'verbose_name': 'Hold List',
                'verbose_name_plural': 'Hold List',
            },
        ),
        migrations.CreateModel(
            name='tbl_note1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev0', models.DateField(blank=True, null=True)),
                ('rev1', models.DateField(blank=True, null=True)),
                ('rev2', models.DateField(blank=True, null=True)),
                ('rev3', models.DateField(blank=True, null=True)),
                ('rev4', models.DateField(blank=True, null=True)),
                ('rev5', models.DateField(blank=True, null=True)),
                ('rev6', models.DateField(blank=True, null=True)),
                ('icn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.tbl_icn')),
            ],
            options={
                'verbose_name': 'Issue Date',
                'verbose_name_plural': 'Issue Date',
            },
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='area_lead',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 6}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_lead', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='checker',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 7}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='designer',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 9}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='iso_controller',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iso_controller', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='location',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='mhi_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims_main.ref_mhi_status'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='mhi_sv',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mhi_sv', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='pfa_checker',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 10}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfa_checker', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='pid_checker',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pid_checker', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='spe_checker',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 11}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spe_checker', to='ims_main.user_detail'),
        ),
        migrations.AddField(
            model_name='tbl_icn',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.ref_unit'),
        ),
        migrations.AddField(
            model_name='ref_area',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.ref_unit', to_field='unit_description'),
        ),
    ]
