# Generated by Django 2.2.5 on 2020-06-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrg_hr_ref', '0003_employeestatuscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeestatuscode',
            name='employeestatusdescription',
            field=models.CharField(max_length=20),
        ),
    ]
