# Generated by Django 2.2.5 on 2020-06-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrg_hr_ref', '0004_auto_20200625_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employeestatuscode',
        ),
    ]
