# Generated by Django 2.2.5 on 2020-06-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrg_hr_ref', '0005_delete_employeestatuscode'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeestatuscode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeestatusdescription', models.CharField(max_length=20)),
            ],
        ),
    ]
