# Generated by Django 3.2.5 on 2021-07-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblhrMaster',
            fields=[
                ('employeeid', models.CharField(db_column='EmployeeID', max_length=4, primary_key=True, serialize=False)),
                ('employeetype', models.CharField(db_column='EmployeeType', max_length=2)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, db_column='NickName', max_length=50, null=True)),
                ('employeestatus', models.IntegerField(blank=True, db_column='EmployeeStatus', null=True)),
                ('gender', models.IntegerField(blank=True, db_column='Gender', null=True)),
                ('civilstatus', models.IntegerField(blank=True, db_column='CivilStatus', null=True)),
                ('dateofbirth', models.DateField(blank=True, db_column='DateofBirth', null=True)),
                ('birthplace', models.CharField(blank=True, db_column='Birthplace', max_length=50, null=True)),
                ('sssno', models.CharField(blank=True, db_column='SSSNo', max_length=12, null=True)),
                ('tin', models.CharField(blank=True, db_column='TIN', max_length=11, null=True)),
                ('philhealthno', models.CharField(blank=True, db_column='PhilHealthNo', max_length=14, null=True)),
                ('pagibigno', models.CharField(blank=True, db_column='PagIbigNo', max_length=14, null=True)),
                ('picture', models.CharField(blank=True, db_column='Picture', max_length=50, null=True)),
                ('designation', models.CharField(blank=True, db_column='Designation', max_length=2, null=True)),
                ('dateemployed', models.DateField(blank=True, db_column='DateEmployed', null=True)),
                ('dateresigned', models.DateField(blank=True, db_column='DateResigned', null=True)),
                ('shiftcode', models.CharField(blank=True, db_column='ShiftCode', max_length=2, null=True)),
                ('projectcode', models.CharField(blank=True, db_column='ProjectCode', max_length=3, null=True)),
                ('height', models.FloatField(blank=True, db_column='Height', null=True)),
                ('weight', models.FloatField(blank=True, db_column='Weight', null=True)),
                ('basic', models.FloatField(blank=True, db_column='Basic', null=True)),
                ('effectivitydate', models.DateField(blank=True, db_column='EffectivityDate', null=True)),
                ('deminimis', models.FloatField(blank=True, db_column='Deminimis', null=True)),
                ('fringe', models.FloatField(blank=True, db_column='Fringe', null=True)),
                ('leavecredits', models.FloatField(blank=True, db_column='LeaveCredits', null=True)),
                ('slcredits', models.FloatField(blank=True, db_column='SLCredits', null=True)),
                ('vlcredits', models.FloatField(blank=True, db_column='VLCredits', null=True)),
                ('taxcode', models.CharField(blank=True, db_column='TaxCode', max_length=50, null=True)),
                ('philhealth', models.FloatField(blank=True, db_column='PhilHealth', null=True)),
                ('oldbasic', models.FloatField(blank=True, db_column='OldBasic', null=True)),
                ('isict', models.IntegerField(blank=True, db_column='isICT', null=True)),
                ('performanceallowance', models.FloatField(blank=True, db_column='PerformanceAllowance', null=True)),
                ('positionfee', models.FloatField(blank=True, db_column='PositionFee', null=True)),
                ('positionfeename', models.CharField(blank=True, db_column='PositionFeeName', max_length=2, null=True)),
                ('performanceallowance0to100', models.FloatField(blank=True, db_column='PerformanceAllowance0to100', null=True)),
                ('singleoccupant', models.FloatField(blank=True, db_column='SingleOccupant', null=True)),
                ('relodginghomenetwork', models.FloatField(blank=True, db_column='RelodgingHomeNetwork', null=True)),
                ('livingallowance', models.FloatField(blank=True, db_column='LivingAllowance', null=True)),
            ],
            options={
                'db_table': 'tblHR_Master',
                'managed': False,
            },
        ),
    ]
