# Generated by Django 3.0.8 on 2020-09-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_projectcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCode',
        ),
    ]
