# Generated by Django 3.0.8 on 2020-10-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriodReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payperiodtype', models.CharField(blank=True, choices=[('REGULAR', 'REGULAR'), ('SPECIAL', 'SPECIAL')], max_length=7, null=True)),
                ('paystart', models.DateField(blank=True, null=True)),
                ('payend', models.DateField(blank=True, null=True)),
                ('modifiedby', models.CharField(blank=True, max_length=50, null=True)),
                ('modifieddate', models.DateField(blank=True, null=True)),
                ('days', models.FloatField(blank=True, null=True)),
                ('locked', models.IntegerField(blank=True, null=True)),
                ('payslipapprove', models.IntegerField(blank=True, null=True)),
                ('approvedate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Standard Payroll Period',
                'verbose_name_plural': 'Standard Payroll Period',
            },
        ),
    ]
