# Generated by Django 3.0.8 on 2020-10-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_acctg', '0002_auto_20201024_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardregister',
            name='namer',
        ),
    ]
