# Generated by Django 3.0.8 on 2021-02-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_web', '0002_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='access',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
