# Generated by Django 2.2.5 on 2020-06-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrg_hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='pictureurl',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
