# Generated by Django 2.2.5 on 2020-06-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrg_hr', '0002_user_detail_pictureurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('employeeid', models.CharField(max_length=4)),
                ('employeetype', models.CharField(max_length=2)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('employeestatus', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('civilstatus', models.IntegerField(blank=True, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=50, null=True)),
                ('sssno', models.CharField(blank=True, max_length=12, null=True)),
                ('tin', models.CharField(blank=True, max_length=11, null=True)),
                ('philhealthno', models.CharField(blank=True, max_length=14, null=True)),
                ('pagibigno', models.CharField(blank=True, max_length=14, null=True)),
                ('picture', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=2, null=True)),
                ('dateemployed', models.DateField(blank=True, null=True)),
                ('dateresigned', models.DateField(blank=True, null=True)),
                ('shiftcode', models.CharField(blank=True, max_length=2, null=True)),
                ('projectcode', models.CharField(blank=True, max_length=3, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('basic', models.FloatField(blank=True, null=True)),
                ('effectivitydate', models.DateField(blank=True, null=True)),
                ('deminimis', models.FloatField(blank=True, null=True)),
                ('fringe', models.FloatField(blank=True, null=True)),
                ('leavecredits', models.FloatField(blank=True, null=True)),
                ('slcredits', models.FloatField(blank=True, null=True)),
                ('vlcredits', models.FloatField(blank=True, null=True)),
                ('taxcode', models.CharField(blank=True, max_length=50, null=True)),
                ('philhealth', models.FloatField(blank=True, null=True)),
                ('oldbasic', models.FloatField(blank=True, null=True)),
                ('isict', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
