# Generated by Django 2.2.5 on 2020-06-25 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrg_hr', '0004_auto_20200625_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblmaster',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrg_hr_ref.gendercode'),
        ),
    ]
