# Generated by Django 2.2.5 on 2020-06-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrg_hr', '0005_auto_20200625_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblmaster',
            name='projectcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrg_hr_ref.projectcode'),
        ),
    ]
