# Generated by Django 2.2.5 on 2020-07-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrg_hr', '0009_remove_user_detail_user_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='user_access',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
