# Generated by Django 3.0.8 on 2020-09-23 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr_ref', '0004_employeetypecode'),
        ('mhiap_hr', '0002_auto_20200923_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_master',
            name='employee_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mhiap_hr_ref.EmployeeTypeCode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hr_master',
            name='employee_id',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
