# Generated by Django 3.0.8 on 2020-09-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr', '0005_auto_20200923_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmaster',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
