# Generated by Django 3.0.8 on 2020-09-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr', '0006_hrmaster_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmaster',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='hr_pic/'),
        ),
    ]
