# Generated by Django 3.0.8 on 2020-09-24 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr_ref', '0006_employeestatuscode'),
        ('mhiap_hr', '0007_auto_20200924_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmaster',
            name='employee_status',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='mhiap_hr_ref.EmployeeStatusCode'),
        ),
    ]
