# Generated by Django 3.0.8 on 2020-10-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr', '0009_hrmasterworkdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmasterworkdetail',
            name='pagibig_no',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
