# Generated by Django 3.0.8 on 2020-10-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr', '0010_auto_20201009_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrmasterworkdetail',
            old_name='employee_id',
            new_name='empl',
        ),
    ]
