# Generated by Django 3.0.8 on 2020-10-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr_ref', '0011_delete_tblplantarea'),
        ('mhiap_hr', '0011_auto_20201009_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmasterworkdetail',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mhiap_hr_ref.DesignationCode'),
        ),
    ]
