# Generated by Django 3.0.8 on 2020-10-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr_ref', '0011_delete_tblplantarea'),
        ('mhiap_hr', '0012_hrmasterworkdetail_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmaster',
            name='employee_id',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='hrmaster',
            name='employee_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mhiap_hr_ref.EmployeeTypeCode'),
        ),
    ]
