# Generated by Django 3.0.8 on 2020-10-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr', '0014_auto_20201012_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmaster',
            name='date_employed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrmaster',
            name='date_resigned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
