# Generated by Django 3.0.8 on 2020-10-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr', '0015_auto_20201012_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmaster',
            name='height',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hrmaster',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
