# Generated by Django 3.0.8 on 2020-10-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr', '0016_auto_20201012_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrMasterAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_address', models.TextField()),
                ('permanent_town', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_province', models.CharField(blank=True, max_length=50, null=True)),
                ('lodging_address', models.TextField()),
                ('lodging_town', models.CharField(blank=True, max_length=50, null=True)),
                ('lodging_province', models.CharField(blank=True, max_length=50, null=True)),
                ('empl_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mhiap_hr.HrMaster')),
            ],
        ),
    ]
