# Generated by Django 3.0.8 on 2020-10-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr', '0017_hrmasteraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrMasterPayrollDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.FloatField(blank=True, null=True)),
                ('deminimis', models.FloatField(blank=True, null=True)),
                ('performance_allowance', models.FloatField(blank=True, null=True)),
                ('fringe', models.FloatField(blank=True, null=True)),
                ('leave_credits', models.FloatField(blank=True, null=True)),
                ('sl_credits', models.FloatField(blank=True, null=True)),
                ('vl_credits', models.FloatField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('empl_payroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mhiap_hr.HrMaster')),
            ],
        ),
    ]
