# Generated by Django 3.0.8 on 2020-10-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr', '0018_hrmasterpayrolldetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HrMasterPayrollDetails',
            new_name='HrMasterPayrollDetail',
        ),
    ]
