# Generated by Django 3.0.8 on 2021-01-18 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management_accounts.Projects')),
            ],
            options={
                'verbose_name': 'Employee List',
            },
        ),
        migrations.CreateModel(
            name='ProjectHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('jan_hrs', models.FloatField(default=0)),
                ('feb_hrs', models.FloatField(default=0)),
                ('mar_hrs', models.FloatField(default=0)),
                ('apr_hrs', models.FloatField(default=0)),
                ('may_hrs', models.FloatField(default=0)),
                ('jun_hrs', models.FloatField(default=0)),
                ('jul_hrs', models.FloatField(default=0)),
                ('aug_hrs', models.FloatField(default=0)),
                ('sep_hrs', models.FloatField(default=0)),
                ('oct_hrs', models.FloatField(default=0)),
                ('nov_hrs', models.FloatField(default=0)),
                ('dec_hrs', models.FloatField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_accounts.Projects')),
            ],
            options={
                'verbose_name': 'No of Project Hour',
                'unique_together': {('project', 'year')},
            },
        ),
    ]
