# Generated by Django 3.0.8 on 2021-01-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0003_auto_20210120_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='emmployee_status',
            field=models.CharField(blank=True, choices=[('1', 'REGULAR PERMANENT'), ('2', 'PROJECT BASE'), ('3', 'FIXED TERM'), ('4', 'CONSULTANT'), ('5', 'REGULAR AP REP')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='emmployee_type',
            field=models.CharField(blank=True, choices=[('1', 'EMPLOYEE'), ('2', 'NON-EMPLOYEE'), ('3', 'OUTSOURCED')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='nationality',
            field=models.CharField(blank=True, choices=[('1', 'FILIPINO'), ('2', 'JAPANESE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='project_type',
            field=models.CharField(blank=True, choices=[('1', 'DESIGNER'), ('2', 'PROJECT ASSISTANT'), ('3', 'COMMON')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
