# Generated by Django 3.0.8 on 2021-01-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0004_auto_20210128_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='emmployee_type',
            new_name='employee_type',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='emmployee_status',
        ),
        migrations.AddField(
            model_name='employees',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('1', 'REGULAR PERMANENT'), ('2', 'PROJECT BASE'), ('3', 'FIXED TERM'), ('4', 'CONSULTANT'), ('5', 'REGULAR AP REP'), ('6', 'PROBATIONARY')], max_length=30, null=True),
        ),
    ]
