# Generated by Django 3.0.8 on 2021-02-08 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0005_auto_20210129_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('active_cases', models.FloatField(default=0)),
                ('recovered', models.FloatField(default=0)),
                ('died', models.FloatField(default=0)),
                ('bed_occpuancy', models.FloatField(default=0)),
                ('bed_occ', models.FloatField(default=0)),
                ('bed_vac', models.FloatField(default=0)),
                ('icu_occ', models.FloatField(default=0)),
                ('icu_vac', models.FloatField(default=0)),
                ('isolation_occ', models.FloatField(default=0)),
                ('isolation_vac', models.FloatField(default=0)),
                ('ward_occ', models.FloatField(default=0)),
                ('ward_vac', models.FloatField(default=0)),
                ('ventilator_occ', models.FloatField(default=0)),
                ('ventilator_vac', models.FloatField(default=0)),
            ],
        ),
    ]
