# Generated by Django 3.0.8 on 2021-02-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0006_covid'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='total_cases',
            field=models.FloatField(default=0),
        ),
    ]
