# Generated by Django 3.0.8 on 2021-02-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0007_covid_total_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
    ]
