# Generated by Django 3.0.8 on 2021-02-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0009_auto_20210209_1458'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='covid',
            table='covid',
        ),
    ]
