# Generated by Django 3.0.8 on 2021-02-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0011_auto_20210210_0813'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='covid',
            table=None,
        ),
    ]
