# Generated by Django 3.0.8 on 2021-02-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0015_auto_20210210_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='bed_occpuancy',
            field=models.FloatField(default=0),
        ),
    ]
