# Generated by Django 3.0.8 on 2021-02-26 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0016_auto_20210211_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True)),
                ('pic', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('1', 'EMPLOYEE'), ('2', 'NON-EMPLOYEE'), ('3', 'OUTSOURCED'), ('4', 'INDIRECT OUTSOURCED')], max_length=30, null=True),
        ),
    ]
