# Generated by Django 3.0.8 on 2021-03-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0017_auto_20210226_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='pic',
            field=models.ImageField(upload_to='static/media/'),
        ),
    ]
