# Generated by Django 3.0.8 on 2021-03-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0020_auto_20210309_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='pic4',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
