# Generated by Django 3.0.8 on 2021-03-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0021_auto_20210310_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='pic3',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='pic4',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/media/'),
        ),
    ]
