# Generated by Django 3.0.8 on 2021-03-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0023_auto_20210312_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='static\\management_main\\img'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='pic2',
            field=models.ImageField(blank=True, default='static\\management_main\\img\\default.jpg', null=True, upload_to='static\\management_main\\img'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='pic3',
            field=models.ImageField(blank=True, default='static\\management_main\\img\\default.jpg', null=True, upload_to='static\\management_main\\img'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='pic4',
            field=models.ImageField(blank=True, default='static\\management_main\\img\\default.jpg', null=True, upload_to='static\\management_main\\img'),
        ),
    ]
