# Generated by Django 3.0.8 on 2021-03-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0024_auto_20210315_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('1', 'REGULAR PERMANENT'), ('2', 'PROJECT BASE'), ('3', 'FIXED TERM'), ('4', 'CONSULTANT'), ('5', 'REGULAR AP REP'), ('6', 'PROBATIONARY'), ('7', 'OUTSOURCED'), ('8', 'IN-ACTIVE')], max_length=30, null=True),
        ),
    ]
