# Generated by Django 3.0.8 on 2021-03-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0026_auto_20210316_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='bed_capacity',
            field=models.ImageField(blank=True, default='static\\management_main\\img\\default.jpg', null=True, upload_to='static\\management_main\\img'),
        ),
        migrations.AddField(
            model_name='covid',
            name='daily_cases',
            field=models.ImageField(blank=True, default='static\\management_main\\img\\default.jpg', null=True, upload_to='static\\management_main\\img'),
        ),
    ]
