# Generated by Django 3.0.8 on 2021-03-19 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0028_headcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'News, Events and Photos'},
        ),
        migrations.AlterModelOptions(
            name='financial',
            options={'verbose_name': 'Financial Status'},
        ),
        migrations.AlterModelOptions(
            name='headcount',
            options={'verbose_name': 'Head Count source file'},
        ),
        migrations.AlterModelOptions(
            name='managers',
            options={'verbose_name': 'Messages from the Managers'},
        ),
    ]
