# Generated by Django 3.0.8 on 2021-03-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0029_auto_20210319_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeehours',
            options={'verbose_name': 'No of Employee Man Hous'},
        ),
        migrations.AlterModelOptions(
            name='headcount',
            options={'verbose_name_plural': 'Head Count source file'},
        ),
    ]
