# Generated by Django 3.0.8 on 2021-03-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0030_auto_20210319_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covid',
            options={'verbose_name_plural': 'Covid Tracker'},
        ),
        migrations.AlterModelOptions(
            name='employeehours',
            options={'verbose_name_plural': 'No of Employee Man Hous'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name_plural': 'Employee List'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'News, Events and Photos'},
        ),
        migrations.AlterModelOptions(
            name='financial',
            options={'verbose_name_plural': 'Financial Status'},
        ),
        migrations.AlterModelOptions(
            name='managers',
            options={'verbose_name_plural': 'Messages from the Managers'},
        ),
        migrations.AlterModelOptions(
            name='projecthours',
            options={'verbose_name_plural': 'No of Project Hour'},
        ),
    ]
