# Generated by Django 3.0.8 on 2021-03-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_main', '0031_auto_20210319_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeehours',
            options={'verbose_name_plural': 'No of Employee Man Hours'},
        ),
        migrations.AlterModelOptions(
            name='projecthours',
            options={'verbose_name_plural': 'No of Project Hours'},
        ),
    ]
