# Generated by Django 3.0.8 on 2020-09-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr_ref', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='civil_status_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_status_description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='employee_status_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_status_description', models.CharField(max_length=20)),
            ],
        ),
    ]
