# Generated by Django 3.0.8 on 2020-09-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mhiap_hr_ref', '0003_auto_20200923_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTypeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('prefix', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
