# Generated by Django 3.0.8 on 2020-09-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr_ref', '0006_employeestatuscode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='access',
            new_name='permission',
        ),
    ]
