# Generated by Django 3.0.8 on 2020-09-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr_ref', '0009_designationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblplantArea',
            fields=[
                ('plant_area_id', models.AutoField(db_column='PLANT_AREA_ID', primary_key=True, serialize=False)),
                ('project_name', models.IntegerField(blank=True, db_column='PROJECT_NAME', null=True)),
                ('plant_area', models.CharField(blank=True, db_column='PLANT_AREA', max_length=50, null=True)),
                ('area_lead', models.CharField(blank=True, db_column='AREA_LEAD', max_length=50, null=True)),
                ('mhi_sv', models.CharField(blank=True, db_column='MHI_SV', max_length=50, null=True)),
                ('checker', models.CharField(blank=True, db_column='CHECKER', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TBLPLANT_AREA',
                'managed': False,
            },
        ),
    ]
