# Generated by Django 3.0.8 on 2020-10-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhiap_hr_ref', '0010_tblplantarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblplantArea',
        ),
    ]
