# Generated by Django 3.0.9 on 2021-05-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Computer Models',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Item Types',
            },
        ),
    ]
