# Generated by Django 3.0.9 on 2021-05-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.CharField(max_length=4, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
