# Generated by Django 3.0.9 on 2021-05-29 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers_app', '0002_usernames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernames',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='model_description',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='item_description',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usernames',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='computer_inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=11, null=True)),
                ('device_name', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('item_status', models.CharField(blank=True, choices=[('IN-USE', 'IN-USE'), ('IN-STOCK', 'IN-STOCK'), ('DEFECTIVE', 'DEFECTIVE')], default='IN-STOCK', max_length=50, null=True)),
                ('item_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers_app.ComputerModel', to_field='model_description')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers_app.ItemType', to_field='item_description')),
                ('item_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers_app.UserNames', to_field='nick_name')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
