# Generated by Django 3.0.9 on 2021-06-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers_app', '0003_auto_20210529_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer_inventory',
            name='item_type',
        ),
        migrations.AddField(
            model_name='computermodel',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers_app.ItemType', to_field='item_description'),
        ),
    ]
