# Generated by Django 3.0.9 on 2021-06-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers_app', '0004_auto_20210602_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_inventory',
            name='item_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
