# Generated by Django 3.0.8 on 2021-02-16 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='health_checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_date', models.DateField()),
                ('nature_of_visit', models.CharField(choices=[('OFFICIAL', 'OFFICIAL'), ('PERSONAL', 'PERSONAL')], default='OFFICIAL', max_length=10)),
                ('body_temp_check', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=3)),
                ('sore_throat', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('body_pain', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('head_ache', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('fever', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('question_two', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('question_three', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('question_four', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('question_five', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_hr.hr_master', to_field='idno')),
            ],
            options={
                'verbose_name_plural': 'Health Checklist',
            },
        ),
    ]
