# Generated by Django 3.0.8 on 2021-02-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ref_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Reference Area',
            },
        ),
        migrations.CreateModel(
            name='ref_mhi_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhi_approve_status_short', models.CharField(max_length=50)),
                ('mhi_approve_status_long', models.CharField(max_length=100)),
                ('model_status', models.CharField(max_length=20)),
                ('mhi_code', models.CharField(max_length=5, unique=True)),
                ('sort_order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Reference MHI Status',
                'verbose_name_plural': 'Reference MHI Status',
            },
        ),
        migrations.CreateModel(
            name='ref_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_description', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Reference Unit',
                'verbose_name_plural': 'Reference Unit',
            },
        ),
        migrations.CreateModel(
            name='ref_user_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_access_description', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reference User Access',
                'verbose_name_plural': 'Reference User Access',
            },
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('pic', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('user_access', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ims_main.ref_user_access', to_field='user_access_description')),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Detail',
            },
        ),
        migrations.CreateModel(
            name='tbl_icn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icn', models.CharField(max_length=5, unique=True)),
                ('line_id', models.CharField(max_length=20)),
                ('latest_issue_date', models.DateField(blank=True, null=True)),
                ('npd', models.FloatField(default=0)),
                ('icn_status', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('REV', 'REV'), ('VOID', 'VOID')], default='NEW', max_length=6, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.ref_area')),
                ('area_lead', models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 6}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_lead', to='ims_main.user_detail')),
                ('checker', models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 7}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to='ims_main.user_detail')),
                ('designer', models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 9}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer', to='ims_main.user_detail')),
                ('iso_controller', models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iso_controller', to='ims_main.user_detail')),
                ('location', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='ims_main.user_detail')),
                ('mhi_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims_main.ref_mhi_status', to_field='mhi_code')),
                ('mhi_sv', models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mhi_sv', to='ims_main.user_detail')),
                ('pfa_checker', models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 10}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfa_checker', to='ims_main.user_detail')),
                ('pid_checker', models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pid_checker', to='ims_main.user_detail')),
                ('spe_checker', models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 11}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spe_checker', to='ims_main.user_detail')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.ref_unit', to_field='unit_description')),
            ],
            options={
                'verbose_name': 'ICN Table',
                'verbose_name_plural': 'ICN Table',
            },
        ),
        migrations.AddField(
            model_name='ref_area',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.ref_unit', to_field='unit_description'),
        ),
    ]
