# Generated by Django 3.0.8 on 2021-02-04 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims_main', '0002_auto_20210204_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_icn',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims_main.ref_area', to_field='area'),
        ),
    ]
