# Generated by Django 3.0.8 on 2021-02-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_main', '0004_auto_20210205_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
