# Generated by Django 3.0.8 on 2021-02-05 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims_main', '0005_auto_20210205_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_icn',
            name='area_lead',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 'Area Lead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_lead', to='ims_main.user_detail', to_field='nickname'),
        ),
        migrations.AlterField(
            model_name='tbl_icn',
            name='checker',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 'Checker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to='ims_main.user_detail', to_field='nickname'),
        ),
        migrations.AlterField(
            model_name='tbl_icn',
            name='designer',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': '3D Designer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer', to='ims_main.user_detail', to_field='nickname'),
        ),
        migrations.AlterField(
            model_name='tbl_icn',
            name='iso_controller',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 'ISO Controller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iso_controller', to='ims_main.user_detail', to_field='nickname'),
        ),
        migrations.AlterField(
            model_name='tbl_icn',
            name='mhi_sv',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 'MHI SV'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mhi_sv', to='ims_main.user_detail', to_field='nickname'),
        ),
        migrations.AlterField(
            model_name='tbl_icn',
            name='pfa_checker',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 'PFA Checker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfa_checker', to='ims_main.user_detail', to_field='nickname'),
        ),
        migrations.AlterField(
            model_name='tbl_icn',
            name='pid_checker',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 'PID Checker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pid_checker', to='ims_main.user_detail', to_field='nickname'),
        ),
        migrations.AlterField(
            model_name='tbl_icn',
            name='spe_checker',
            field=models.ForeignKey(blank=True, default='', limit_choices_to={'user_access': 'SPE Checker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spe_checker', to='ims_main.user_detail', to_field='nickname'),
        ),
    ]
